# Generated by Django 4.0.2 on 2023-05-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo_shop', '0008_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(default='hey', max_length=400),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='hey', max_length=50),
        ),
    ]
