# Generated by Django 4.0.2 on 2023-05-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo_shop', '0009_alter_contact_message_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='hey@1234.com', max_length=254),
        ),
    ]
